// <auto-generated />
using System;
using Duties.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Duties.Infrastructure.Migrations
{
    [DbContext(typeof(DutiesContext))]
    partial class DutiesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Duties.Domain.AggregatesModel.DutyAggregate.Duty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("HourEnd")
                        .HasColumnType("int");

                    b.Property<int>("HourStart")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NodeStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("_createdTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 1, 10, 18, 5, 58, 648, DateTimeKind.Utc).AddTicks(6572));

                    b.Property<bool>("_isNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IsNew")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("DUTIES","duties_db");
                });

            modelBuilder.Entity("Duties.Domain.AggregatesModel.ResourceAggregate.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ResourceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceCode")
                        .IsUnique();

                    b.ToTable("RESOURCES","duties_db");
                });
#pragma warning restore 612, 618
        }
    }
}
